task_base:
  task_name: passive_biv
  model_name: fe_heart_sage_v2
  exp_name: rec_2
  overwrite_exp_folder: True
  gpu: True
  cuda_core: "cuda:1"
  gpu_num: 1
  #  log_dir: "./"
task_trainer:
  epochs: 5001
  optimizer_param:
    name: adam
    learning_rate: 0.00001  # Learning rate for training the network
  loss_param:
    name: euclidean_distance_mse
  metrics_param:
    - mean_absolute_error
  callback_param:
    tensorboard:
      profiler: False
    model_checkpoint:
      save_freq: 100
      save_model_freq: 200
    logs:
      update_freq: 1
      save_config: True
      save_task_code: True
    scheduling:
      avoid_work_hour: True
  dataset_param:
    batch_size: 20
    val_batch_size: 20
    num_workers: 8
    prefetch_factor: 2
    val_prefetch_factor: 2
  static_graph: False
  init_model_weights: True
task_train:
  neighbour_layers: 1
  node_input_mlp_layer:
    unit_sizes: [17, 128, 128, 40]
    layer_norm: True
    activation: tanh
  message_passing_layer:
    agg_method: MeanAggregator
    layer_threshold: [20, 50, 80, 90, 100]
    layer_selected_node_num: [10, 10, 10, 10, 10]
    agg_layer:
      agg_dim: 2
      keep_dim: False
    node_mlp_layer:
      unit_sizes: [80, 128, 128, 40]
      layer_norm: True
      activation: tanh
    edge_mlp_layer:
      unit_sizes: [89, 128, 128, 40]
      layer_norm: True
      activation: tanh
  theta_input_mlp_layer:
    unit_sizes: [66, 128, 128, 48]
    layer_norm: True
    activation: tanh
  decoder_layer:
    unit_sizes: [88, 128, 128, 1]
    layer_norm: False
    activation: tanh
    output_dim: 4
  labels:
    - displacement
    # - stress

